## Numpy Array operations 


In [2]:
import numpy as np

In [ ]:
arr = np.arange(1,13)
print("original array",arr)
print("Basic Slicing ",arr[2:7])
print("Advanced Slicing ",arr[1:10:4])
print("negative Slicing ",arr[-8:-3])
# condition of array 
condition = arr > 5
conditionArray = np.where(condition);
#with 2 condition 
conditionArray2 = np.where(arr > 5, arr < 10, arr) # if else condition type this 
print("condition array",conditionArray)

original array [ 1  2  3  4  5  6  7  8  9 10 11 12]
Basic Slicing  [3 4 5 6 7]
Advanced Slicing  [ 2  6 10]
negative Slicing  [5 6 7 8 9]
condition array (array([ 5,  6,  7,  8,  9, 10, 11]),)


In [13]:
arr2d = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15]])
# print("2d array",arr2d)
print("specific element ", arr2d[1,3])
print("col target ",arr2d[:,3])

specific element  9
col target  [ 4  9 14]


## Adding & removing Data

In [24]:
arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([[7,8,9],[10,11,12]])
# combine 2 array
combined = np.concatenate((arr1,arr2),axis=0)
# column wise combine
col_combined = np.concatenate((arr1,arr2),axis=1)
print("combined array",combined)
print("column wise combined array",col_combined)



combined array [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
column wise combined array [[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]


## array compatibility 


In [31]:
array = np.array([[1,2,3],[4,5,6]])
array2 = np.array([[7,8,9],[10,11,12]])
array3 = np.array([[13,15],[16,18]])

print("compatible array",array.shape == array2.shape == array3.shape) # depth wise

# original array
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
new_row = np.array([[10,11,12]])
# adding new row
arr = np.vstack([arr,new_row])
print("after adding new row",arr)
#h stack 
new_col = np.array([[13],[14],[15],[16]])
arr = np.hstack([arr,new_col])
print("after adding new col",arr)

compatible array False
after adding new row [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
after adding new col [[ 1  2  3 13]
 [ 4  5  6 14]
 [ 7  8  9 15]
 [10 11 12 16]]
