## Numpy array & basics 
learn about numpy

In [2]:
import numpy as np

Creating arrays from scratch

In [3]:
zeros = np.zeros((3,4))
print("print array of zero",zeros)

print array of zero [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
onces = np.ones((2,3),dtype=np.int16)
print("print array of ones",onces)

print array of ones [[1 1 1]
 [1 1 1]]


In [7]:
full = np.full((2,3),7)
print("print array of full",full) 

print array of full [[7 7 7]
 [7 7 7]]


In [ ]:
#imp. 
random = np.random.random((2,4)) 
print("print array of random",random)

print array of random [[5.23352209 6.53673866 0.06923059 8.3414515 ]
 [9.65940472 0.24547082 1.46554136 6.60786456]]


Vector , Matrix & tensor


In [19]:
vector = np.array([1,2,3])
# print("print vector",vector)

matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])
# print("print matrix",matrix)

tensor = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[19,20,21],[22,23,24],[25,26,27]]])
print("print tensor",tensor)


print tensor [[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[19 20 21]
  [22 23 24]
  [25 26 27]]]


Array Properties 


In [21]:
arr = np.array([[1,2,3],[4,5,6]], dtype = np.int8)
print("shape of array",arr.shape)
print("number of dimension",arr.ndim)
print("data type of array",arr.dtype)
print("size of array",arr.size)

shape of array (2, 3)
number of dimension 2
data type of array int8
size of array 6


Array Reshaping 

In [ ]:
arr = np.arange(1,13)
reshaped = arr.reshape((3,4))
print("original array",arr)
print("reshaped array",reshaped)
# FLATTENED return copy of array
# important it return original array in 1D
raveled = reshaped.ravel()
print("raveled array",raveled)

# TRANSPOSE row to column and column to row
transposed = reshaped.T
print("transposed array",transposed)

original array [ 1  2  3  4  5  6  7  8  9 10 11 12]
reshaped array [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
raveled array [ 1  2  3  4  5  6  7  8  9 10 11 12]
transposed array [[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
